.TH FastPhoto 1 "February 2006"
.SH NAME
fastphoto \- high performance photo rescaler
.SH SYNOPSIS
.B fastphoto
[\fIOPTION\fR]...
.SH DESCRIPTION
.PP
Rescale JPEG image files.
.PP
fastphoto is a high-performance rescaling tool for photographic images. It
can be installed on a web server as a handler for files of type image/jpeg,
providing fast server-side resizing with (optional) transparent caching.
.PP
fastphoto uses libepeg, a high-performance JPEG resizing library which
decodes only the DCT coefficients needed to reconstruct an image of the
desired size, and avoids colorspace conversions (unless converting color
images to grayscale).
.PP
fastphoto preserves the aspect of the original file unless both width and
height options are specified.

.SH "COMMANDLINE OPTIONS"
.PP
\fBScale options\fR
.TP
\fB\-w\fR, \fB\-\-width\fR
Set the width of the output image.
.TP
\fB\-h\fR, \fB\-\-height\fR
Set the height of the output image.
.TP
\fB\-s\fR, \fB\-\-scale\fR
Set the scale as a percentage
.PP
\fBOutput options\fR
.TP
\fB\-q\fR, \fB\-\-quality\fR
Set the output quality as a percentage
.TP
\fB\-G\fR, \fB\-\-gray\fR
Convert to grayscale
.PP
\fBInformational options\fR
.TP
\fB\-i\fR, \fB\-\-info\fR
Display information about the given image and exit
.PP
\fBMiscellaneous options\fR
.TP
\fB\-H\fR, \fB\-\-help\fR
display usage information and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Print informative messages. Additional instances of \fI-v\fR raise the
debugging level, ie. print more information.
.TP
\fB\-V\fR, \fB\-\-version\fR
output version information and exit
.PP
.SH "SERVER CONFIGURATION"
fastphoto can be installed as a handler for files of type image/jpeg.

For more information see http://www.kfish.org/software/fastphoto

.SH "SEE ALSO"
httpd(8), apache(8)

.SH AUTHOR
Conrad Parker <conrad@metadecks.org>, February 2006

Epeg by Carsten Haitzler (the Rasterman).
